---
- hosts: all
  become: true
  gather_facts: true

  vars:
    apache_package: apache2
    php_package: libapache2-mod-php

  tasks:
    - name: Install Apache and PHP on Ubuntu
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Update repository index on Fedora
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: yes
        use_backend: dnf4
      when: ansible_distribution == "Fedora"
