---
- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update repository index on Ubuntu
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Update repository index on Fedora
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: yes
        use_backend: dnf4
      when: ansible_distribution == "Fedora"

    - name: Install Apache package on Ubuntu
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache package on Fedora
      ansible.builtin.dnf:
        name: httpd
        state: present
        use_backend: dnf4
      when: ansible_distribution == "Fedora"

    - name: Install PHP support on Ubuntu
      ansible.builtin.apt:
        name: php
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install PHP support on Fedora
      ansible.builtin.dnf:
        name: php
        state: present
        use_backend: dnf4
      when: ansible_distribution == "Fedora"

